name: Meio.Autocomplete
author: fabiomiranda
category: Forms
tags: [input, autocomplete]
demo: http://mootools.net/shell/jRRbE/2/
docs: http://www.meiocodigo.com/projects/meio-autocomplete/
current: 0.83
