name: Meio.Autocomplete
web: "[mootools.net/forge/p/meio_autocomplete](http://mootools.net/forge/p/meio_autocomplete)"
authors: "[Fábio M. Costa](http://meiocodigo.com/)"
description: "Meio.Autocomplete - A mootools plugin for enabling autocomplete of a text input or textarea."
license: "MIT License"
copyright: "&copy; 2010, Fábio M. Costa"

sources:
  - "Source/Meio.Autocomplete.js"

# Values for MooTools forge

author: fabiomiranda
current: 1.0
category: Forms
tags: [input, autocomplete]
docs: http://meiocodigo.com/projects/meio-autocomplete/
demo: http://jsfiddle.net/fabiomcosta/eZpuL/